services:
  - type: web
    name: taita-cms
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://api.taita.blog
      - key: VITE_SITE_NAME
        value: Taita Blog
      - key: VITE_SITE_URL
        value: https://taita.blog
      - key: VITE_TENANT_DOMAIN
        value: taita.blog
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
