services:
  - type: web
    name: taita-cms
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    # No startCommand needed for static sites
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://taita-api.onrender.com
      - key: VITE_SITE_NAME
        value: Taita Blog
      - key: VITE_SITE_URL
        value: https://taita.blog
      - key: VITE_TENANT_DOMAIN
        value: taita.blog
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      # Redirección explícita para rutas anidadas
      - type: rewrite
        source: /cms/*
        destination: /index.html
      - type: rewrite
        source: /super-admin/*
        destination: /index.html
      # Redirección general para todas las demás rutas
      - type: rewrite
        source: /*
        destination: /index.html
